### ISSUE TITLE
IsoCon breaks for networkx v2.4

### ISSUE THREAD

**Issue by ksahlin** [ksahlin/IsoCon#6]
When installing IsoCon with dependency networks v2.4 the following error occurs:
```
isolated: 0
Number of edges: 84000
Total edit distance: 12122653
Avg ed (ed/edges): 144.31729761904762
Traceback (most recent call last):
  File "/home/alice.namias/.local/bin/IsoCon", line 292, in <module>
    run_pipeline(params)
  File "/home/alice.namias/.local/bin/IsoCon", line 159, in run_pipeline
    candidate_file, read_partition, to_realign = isocon_get_candidates.find_candidate_transcripts(params.read_file, params)
  File "/home/alice.namias/.local/lib/python3.6/site-packages/modules/isocon_get_candidates.py", line 129, in find_candidate_transcripts
    G_star, graph_partition, M, converged = partitions.partition_strings(S, params)
  File "/home/alice.namias/.local/lib/python3.6/site-packages/modules/partitions.py", line 420, in partition_strings
    G_star, converged = graphs.construct_exact_nearest_neighbor_graph(S, params)
  File "/home/alice.namias/.local/lib/python3.6/site-packages/modules/graphs.py", line 63, in construct_exact_nearest_neighbor_graph
    if G.node[s1]["degree"] > 1:
AttributeError: 'DiGraph' object has no attribute 'node'
```

**Comment by ksahlin** [comment]
fixed in IsoCon v0.3.3, commit  6287685
